name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
#     windows-latest, mac-os-latest
#     runs-on: ${{ matrix.os }}

#     strategy:
#         matrix:
#             os: [windows-latest, mac-os-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: nopw_tr
