name: release
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
#     windows-latest, mac-os-latest
#     runs-on: ${{ matrix.os }}

#     strategy:
#         matrix:
#             os: [windows-latest, mac-os-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.3'
      - name: Build
        run: go build -v ./...
      - run: ./nopw_tr
